### ISSUE TITLE
Import U-ANT feature set

### ISSUE THREAD

**Issue by ghost** [lukealford/aussiebb_tray#10]
### New network health check system

**Expectations:** Check latency to national and international locations, check if on CGNAT, check if IPv6 is enabled

**Reason** Giving users a basic insight into how there AussieBB network is going can be helpful to troubleshoot issues and will be lightweight enough to fall into AUNT.

**Todo:**
- [x] Check if on CGNAT
- [x] Check if IPv6 is enabled
- [x] Check national and international latency.
- [x] Add UI

**Comment by ghost** [comment]
This is now completed.
