### ISSUE TITLE
Watch for cookie expire

### ISSUE THREAD

**Issue by lukealford** [lukealford/aussiebb_tray#9]
### Enhancement to the auth system

**Expectations:** Store response from /login and check if cookie expires in 180 days or less.

**Reason** Save having to store user login details at all since we can keep them auto signed in with just the cookie.

**Todo:**
- [x] Store the response from login in a electron-store
- [x] Add a function to check `expiresIn` to see if it's less than 180 days away
- [x] If less than 180 days away renew cookie with `refreshToken`

**Comment by lukealford** [comment]
This has been completed with commit 9e9a5dd14cba1f671820ce5d96d8fbfc264f50c4
